language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.3
    - android-30

  licenses:
    - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew

script: ./gradlew connectedAndroidTest