language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.3

  licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew

script: ./gradlew clean test build